# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: API Test Automation

on:
  push:
    branches: [ main,TestBranch,master ]
  pull_request:
    branches: [ main,TestBranch,master ]
  schedule:
    # Runs twice: daily at 2 AM UTC and Monday/Thursday at 2 PM UTC
    - cron: '37 18 * * *'     # Daily at  11PM UTC
    - cron: '0 17 * * 1,4'  # Monday and Thursday at 2 PM UTC

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'
    - name: Run API Tests
      run: mvn clean test -Dsuite=testng -X
      working-directory: ./APIAutomationProject
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          APIAutomationProject/test-output/reports/
          APIAutomationProject/target/surefire-reports/
          APIAutomationProject/logs/
    
    - name: Publish Test Report
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: TestNG Results
        path: APIAutomationProject/target/surefire-reports/junitreports/TEST-*.xml
        reporter: java-junit

  
